### ISSUE TITLE
安卓顶部不显示导航信息

### ISSUE THREAD

**Issue by wj-1993** [yz1311/react-native-amap-navi#5]
sdk：7.7.1

之前版本的sdk好像是可以显示的，请问有什么解决办法

![WechatIMG585](https://user-images.githubusercontent.com/13558164/102679727-cbaafc80-41ec-11eb-9635-402d0f9cd176.jpeg)

**Comment by yz1311** [comment]
请问你是更改了库里面的导航库的版本号吗？

**Comment by wj-1993** [comment]
定时器抖动上下抖动图层-1px就可以了
